apiVersion: batch/v1
kind: Job
metadata:
  name: combine
spec:
  completions: 40
  parallelism: 5
  template:
    metadata:
      name: combine
    spec:
      containers:
      - name: combine
        image: soltysh/movie
        volumeMounts:
          name: data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: /tmp/data
