apiVersion: batch/v1
kind: Job
metadata:
  name: simple-render
spec:
  template:
    metadata:
      name: simple-render
    spec:
      containers:
      - name: simple-render
        image: soltysh/render
        command:
        - /run.sh
        - http://192.168.121.118:8000/01.py
        volumeMounts:
        - name: data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data
        hostPath:
          path: /tmp/data
